### ISSUE TITLE
facing error for unpickling

### ISSUE THREAD

**Issue by aniruddha08112003** [bibek376/Housing_Price_Prediction#1]
model=pickle.load(open('Housing_Model','rb'))
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by bibek376** [comment]
![Screenshot from 2024-03-13 23-01-54](https://github.com/bibek376/Housing_Price_Prediction/assets/72462017/f6a9e0fe-46a2-4f39-9fec-4c36d8bcfddb)

It's because model size 4kb after cloning the repo. If you can want complete model i can send you via drive.

**Comment by bibek376** [comment]
You can download the data file used in this project by using the following link:

`wget -O $HOME/Housing_Model "https://tinyurl.com/35u8z59s"`
